// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ttmpostgres

import (
	"database/sql"
)

type Session struct {
	ID        int32
	TaskID    sql.NullInt32
	StartTime sql.NullTime
	EndTime   sql.NullTime
}

type Task struct {
	ID          int32
	Title       sql.NullString
	Description sql.NullString
	Category    sql.NullString
	Priority    sql.NullString
	Status      sql.NullString
	OpenedAt    sql.NullTime
	ClosedAt    sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
