// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.postgres.sql

package ttmpostgres

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (task_id, start_time, end_time)
VALUES ($1, $2, $3)
RETURNING id, task_id, start_time, end_time
`

type CreateSessionParams struct {
	TaskID    sql.NullInt32
	StartTime sql.NullTime
	EndTime   sql.NullTime
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.TaskID, arg.StartTime, arg.EndTime)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, description, category, priority, status, opened_at, closed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, description, category, priority, status, opened_at, closed_at, created_at, updated_at
`

type CreateTaskParams struct {
	Title       sql.NullString
	Description sql.NullString
	Category    sql.NullString
	Priority    sql.NullString
	Status      sql.NullString
	OpenedAt    sql.NullTime
	ClosedAt    sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Priority,
		arg.Status,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionsByTaskID = `-- name: GetSessionsByTaskID :many
SELECT id, task_id, start_time, end_time FROM sessions
WHERE task_id = $1
`

func (q *Queries) GetSessionsByTaskID(ctx context.Context, taskID sql.NullInt32) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByTimeRange = `-- name: GetSessionsByTimeRange :many
SELECT id, task_id, start_time, end_time FROM sessions
WHERE start_time >= $1 AND end_time <= $2
`

type GetSessionsByTimeRangeParams struct {
	StartTime sql.NullTime
	EndTime   sql.NullTime
}

func (q *Queries) GetSessionsByTimeRange(ctx context.Context, arg GetSessionsByTimeRangeParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByTimeRange, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, title, description, category, priority, status, opened_at, closed_at, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, category, priority, status, opened_at, closed_at, created_at, updated_at FROM tasks
WHERE 
    (
        ($1 IS NULL OR title LIKE '%' || $1 || '%')
        OR ($2 IS NULL OR description LIKE '%' || $2 || '%')
    )
    AND ($3 IS NULL OR category = $3)
    AND ($4 IS NULL OR priority = $4)
    AND ($5 IS NULL OR status = $5)
`

type ListTasksParams struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskField = `-- name: UpdateTaskField :one
UPDATE tasks
SET 
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    category = COALESCE($3, category),
    priority = COALESCE($4, priority),
    status = COALESCE($5, status),
    opened_at = COALESCE($6, opened_at),
    closed_at = COALESCE($7, closed_at),
    updated_at = $8
WHERE id = $9
RETURNING id, title, description, category, priority, status, opened_at, closed_at, created_at, updated_at
`

type UpdateTaskFieldParams struct {
	Title       sql.NullString
	Description sql.NullString
	Category    sql.NullString
	Priority    sql.NullString
	Status      sql.NullString
	OpenedAt    sql.NullTime
	ClosedAt    sql.NullTime
	UpdatedAt   sql.NullTime
	ID          int32
}

func (q *Queries) UpdateTaskField(ctx context.Context, arg UpdateTaskFieldParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskField,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Priority,
		arg.Status,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
