# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  release:
    types:
      - published

jobs:
  package-windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.3'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y nsis

    - name: Build installer
      shell: bash
      run: make package-windows VERSION="${{ github.event.release.tag_name }}"

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: ttm-setup
        path: dist/ttm_setup.exe

  package-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.3'

    - name: Build Debian package
      run: make package-linux VERSION="${{ github.event.release.tag_name }}"

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v4
      with:
        name: ttm-deb
        path: dist/ttm.deb

  upload-release-asset:
    needs:
    - package-windows
    - package-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download installer artifact
      uses: actions/download-artifact@v4
      with:
        name: ttm-setup
        path: release

    - name: Download Debian package artifact
      uses: actions/download-artifact@v4
      with:
        name: ttm-deb
        path: release

    - name: Upload release assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${{ github.event.release.tag_name }}" \
          release/ttm_setup.exe \
          release/ttm.deb \
          --repo "${{ github.repository }}"