// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ttmpostgres

import (
	"database/sql"
)

type Session struct {
	ID        int64
	TaskID    sql.NullInt64
	StartTime sql.NullTime
	EndTime   sql.NullTime
}

type Tag struct {
	ID     int64
	TaskID sql.NullInt64
	Tag    sql.NullString
}

type Task struct {
	ID          int64
	Title       sql.NullString
	Description sql.NullString
	Category    sql.NullString
	Priority    sql.NullString
	Status      sql.NullString
	OpenedAt    sql.NullTime
	ClosedAt    sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
