// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.postgres.sql

package ttmpostgres

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (task_id, content, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, content, created_at, updated_at
`

type CreateNoteParams struct {
	TaskID    sql.NullInt64
	Content   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.TaskID,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (task_id, start_time, end_time)
VALUES ($1, $2, $3)
RETURNING id, task_id, start_time, end_time
`

type CreateSessionParams struct {
	TaskID    sql.NullInt64
	StartTime sql.NullTime
	EndTime   sql.NullTime
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.TaskID, arg.StartTime, arg.EndTime)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (task_id, tag)
VALUES ($1, $2)
RETURNING id, task_id, tag
`

type CreateTagParams struct {
	TaskID sql.NullInt64
	Tag    sql.NullString
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.TaskID, arg.Tag)
	var i Tag
	err := row.Scan(&i.ID, &i.TaskID, &i.Tag)
	return i, err
}

const createTags = `-- name: CreateTags :many
INSERT INTO tags (task_id, tag)
VALUES ($1, $2)
RETURNING id, task_id, tag
`

type CreateTagsParams struct {
	TaskID sql.NullInt64
	Tag    sql.NullString
}

func (q *Queries) CreateTags(ctx context.Context, arg CreateTagsParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, createTags, arg.TaskID, arg.Tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.TaskID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, description, priority, status, opened_at, closed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, description, priority, status, opened_at, closed_at, created_at, updated_at
`

type CreateTaskParams struct {
	Title       sql.NullString
	Description sql.NullString
	Priority    sql.NullString
	Status      sql.NullString
	OpenedAt    sql.NullTime
	ClosedAt    sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTagsByTaskID = `-- name: DeleteTagsByTaskID :exec
DELETE FROM tags
WHERE task_id = $1
`

func (q *Queries) DeleteTagsByTaskID(ctx context.Context, taskID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteTagsByTaskID, taskID)
	return err
}

const getNotesByTaskID = `-- name: GetNotesByTaskID :many
SELECT id, task_id, content, created_at, updated_at FROM notes
WHERE task_id = $1
`

func (q *Queries) GetNotesByTaskID(ctx context.Context, taskID sql.NullInt64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByTaskID = `-- name: GetSessionsByTaskID :many
SELECT id, task_id, start_time, end_time FROM sessions
WHERE task_id = $1
`

func (q *Queries) GetSessionsByTaskID(ctx context.Context, taskID sql.NullInt64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByTimeRange = `-- name: GetSessionsByTimeRange :many
SELECT id, task_id, start_time, end_time FROM sessions
WHERE start_time >= $1 AND end_time <= $2
`

type GetSessionsByTimeRangeParams struct {
	StartTime sql.NullTime
	EndTime   sql.NullTime
}

func (q *Queries) GetSessionsByTimeRange(ctx context.Context, arg GetSessionsByTimeRangeParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByTimeRange, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByTaskID = `-- name: GetTagsByTaskID :many
SELECT id, task_id, tag FROM tags
WHERE task_id = $1
`

func (q *Queries) GetTagsByTaskID(ctx context.Context, taskID sql.NullInt64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.TaskID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, title, description, priority, status, opened_at, closed_at, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT tag, COUNT(DISTINCT task_id) AS task_count
FROM tags
WHERE tag IS NOT NULL AND tag <> ''
GROUP BY tag
ORDER BY LOWER(tag), tag
`

type ListTagsRow struct {
	Tag       sql.NullString
	TaskCount int64
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.Tag, &i.TaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, priority, status, opened_at, closed_at, created_at, updated_at FROM tasks
WHERE
  (
    $1 IS NULL
    OR $1 = ''
    OR priority IN (SELECT value FROM json_each($1))
  )
  AND (
    $2 IS NULL
    OR $2 = ''
    OR status IN (SELECT value FROM json_each($2))
  )
`

type ListTasksParams struct {
	PrioritiesJSON interface{}
	StatusesJSON   interface{}
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, arg.PrioritiesJSON, arg.StatusesJSON)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskField = `-- name: UpdateTaskField :one
UPDATE tasks
SET 
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    priority = COALESCE($3, priority),
    status = COALESCE($4, status),
    opened_at = COALESCE($5, opened_at),
    closed_at = COALESCE($6, closed_at),
    updated_at = $7
WHERE id = $8
RETURNING id, title, description, priority, status, opened_at, closed_at, created_at, updated_at
`

type UpdateTaskFieldParams struct {
	Title       sql.NullString
	Description sql.NullString
	Priority    sql.NullString
	Status      sql.NullString
	OpenedAt    sql.NullTime
	ClosedAt    sql.NullTime
	UpdatedAt   sql.NullTime
	ID          int64
}

func (q *Queries) UpdateTaskField(ctx context.Context, arg UpdateTaskFieldParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskField,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
